GB_17_Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('seminar1app.urls')),
    path('seminarsapp/', include('seminarsapp.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

seminar1app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

seminarsapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('client-orders/<int:client_id>/<int:days>/', views.client_orders, name='client_orders'),
    path('product-add', views.product_add, name='product_add'),
]

seminarsapp/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = PhoneNumberField(unique=True, null=False, blank=False, region='RU')
    client_address = models.CharField(max_length=500)
    client_registration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f'Name: {self.name}\nEmail: {self.email}\nPhone Number: {self.phone_number}\nAddress: {self.client_address}\n'
            f'Registration Date: {self.client_registration_date}')


class Product(models.Model):
    product_name = models.CharField(max_length=100)
    product_description = models.TextField()
    product_price = models.DecimalField(max_digits=8, decimal_places=2)
    product_count = models.IntegerField()
    product_date_added = models.DateTimeField(auto_now_add=True)
    product_image = models.ImageField(blank=True, null=True, upload_to='seminarsapp/')

    def __str__(self):
        return (f'Product Name: {self.product_name}\nProduct Description: {self.product_description}\n'
                f'Product Price: ${self.product_price}\nProduct Count: {self.product_count}')


class Order(models.Model):
    customer = models.ForeignKey(Client, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product)
    order_price = models.DecimalField(max_digits=8, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.customer.name} | {self.product.name}'


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.order.product.name} | {self.product.product_name} | {self.order.customer.id}'

seminarsapp/forms.py
from datetime import date
from django import forms
from .models import Product


class AddProductForm(forms.Form):
    product_name = forms.CharField(template_name='Название товара', max_length=100,
                                   widget=forms.TextInput(attrs={'class': 'form-control'}))
    product_description = forms.CharField(template_name='Описание товара',
                                          widget=forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}))
    product_price = forms.DecimalField(template_name='Стоимость товара', max_digits=8, decimal_places=2,
                                       widget=forms.NumberInput(attrs={'class': 'form-control'}))
    product_count = forms.IntegerField(template_name='Количество товара',
                                       widget=forms.NumberInput(attrs={'class': 'form-control'}))
    product_date_added = forms.DateField(template_name='Дата добавления товара', initial=date.today(),
                                         widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))
    product_image = forms.ImageField(template_name='Изображение товара',
                                     widget=forms.FileInput(attrs={'class': 'form-control'}))

# class AddProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = '__all__'

seminarsapp/views.py
import logging

from django.shortcuts import render, redirect
from django.db.models import F
from django.core.files.storage import FileSystemStorage
from .models import Client, OrderProduct, Product
from .forms import AddProductForm
from django.utils import timezone
from datetime import timedelta

logger = logging.getLogger(__name__)


def index(request):
    logger.info('Index page accessed')
    all_clients = Client.objects.all()
    context = {
        'title': 'All clients',
        'h1': 'all clients list',
        'clients': all_clients,
    }
    print(all_clients)
    return render(request, 'seminarsapp/index.html', context)


def client_orders(request, client_id, days):
    logger.info('Client orders list page accessed')
    date = timezone.now() - timedelta(days=days)
    products = OrderProduct.objects.prefetch_related('order', 'product').filter(order__order_date__gte=date,
                                                                                order__customer=client_id).values(
        product_name=F('product__product_name'), product_price=F('product__product_price')).distinct()
    context = {
        'title': "Customer's orders",
        'h1': days,
        'products': products,
    }
    return render(request, 'seminarsapp/client-orders.html', context)


def product_add(request):
    if request.method == 'POST' and request.FILES:
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product_name = form.cleaned_data['product_name']
            product_description = form.cleaned_data['product_description']
            product_price = form.cleaned_data['product_price']
            product_count = form.cleaned_data['product_count']
            product_date_added = form.cleaned_data['product_date_added']
            product_image = form.cleaned_data['product_image']
            logger.info('Получены данные о новом продукте')
            new_product = Product(product_name=product_name, product_description=product_description,
                                  product_price=product_price, product_count=product_count,
                                  product_date_added=product_date_added, product_image=product_image)
            new_product.save()
            logger.info('Данные о новом продукты сохранены')
        return redirect(product_add)
    else:
        form = AddProductForm()
        context = {
            'title': 'Add Product',
            'form': form,
        }
    return render(request, 'seminarsapp/product-add.html', context)

# def product_add(request):
#     if request.method == 'POST':
#         form = AddProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#         return redirect(product_add)
#     else:
#         form = AddProductForm()
#         context = {
#             'title': 'Add Product',
#             'form': form,
#         }
#     return render(request, 'seminarsapp/product-add.html', context)

templates/seminarsapp/client-orders.html
{% extends 'base.html' %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}
    <p class="h1 text-center">
        Список продуктов, которые заказал клиент {{ client_id }} за {{ h1|capfirst }} дней
    </p>
    <div class="table-all-client-orders">
        <table class="table table-dark table-hover">
            <thead class="table-secondary">
            <tr>
                <th scope="col">Product name</th>
                <th scope="col">Product price</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.product_price }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'index' %}">Назад</a>
    </div>
{% endblock %}

templates/seminarsapp/img-add.html
{% extends 'base.html' %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_div }}
        <input type="submit" value="Добавить">
    </form>
{% endblock %}

templates/seminarsapp/index.html
{% extends 'base.html' %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}
    <p class="h1 text-center">
        {{ h1|capfirst }}
    </p>
    <div class="table-all-clients">
        <table class="table table-dark table-hover">
            <thead class="table-secondary">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Orders</th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr>
                    <th scope="row">{{ client.id }}</th>
                    <td>{{ client.name }}</td>
                    <td>{{ client.email }}</td>
                    <td>{{ client.phone_number }}</td>
                    <td><a href="{% url 'client_orders' client.id 7 %}">Customer's orders {{ client.id }} in the last 7
                        days</a><br/>>
                        <a href="{% url 'client_orders' client.id 30 %}">Customer's orders {{ client.id }} in the last
                            30 days</a><br/>>
                        <a href="{% url 'client_orders' client.id 365 %}">Customer's orders {{ client.id }} in the last
                            365 days</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {#    <div class="choice-form">#}
    {#        <p class="h3">#}
    {#            Для просмотра заказов по определенному клиенту выберите его номер из списка ниже:#}
    {#        </p>#}
    {#        <div class="input-group">#}
    {#            <form method="post" action="client-orders/">#}
    {#                {% csrf_token %}#}
    {#                <select class="form-select" id="inputGroupSelect04" aria-label="Выбор ID клиента">#}
    {#                    <option selected>Выберите ID клиента</option>#}
    {#                    {% for client in clients %}#}
    {#                        <option id="{{ client.id }}" name="client_id" value="{{ client.id }}">{{ client.id }}</option>#}
    {#                    {% endfor %}#}
    {#                </select>#}
    {#            <button class="btn btn-outline-secondary" type="button">Вперед</button>#}
    {#                <input id="clientIDBtn" type="submit" value="Вперед">#}
    {#            </form>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

templates/seminarsapp/product-add.html
{% extends 'base.html' %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data" class="row g-2 mx-3 my-2">
        {% csrf_token %}
        <div class="col-12">
            <label for="id_product_name" class="form-label">{{ form.product_name.template_name }}</label>
            {{ form.product_name }}
        </div>
        <div class="col-12">
            <label for="id_product_description"
                   class="form-label">{{ form.product_description.template_name }}</label>
            {{ form.product_description }}
        </div>
        <div class="col-md-4">
            <label for="id_product_price" class="form-label">{{ form.product_price.template_name }}</label>
            {{ form.product_price }}
        </div>
        <div class="col-md-4">
            <label for="id_product_count" class="form-label">{{ form.product_count.template_name }}</label>
            {{ form.product_count }}
        </div>
        <div class="col-md-4">
            <label for="id_product_date_added"
                   class="form-label">{{ form.product_date_added.template_name }}</label>
            {{ form.product_date_added }}
        </div>
        <div class="col-12">
            <label for="id_product_image" class="form-label">{{ form.product_image.template_name }}</label>
            {{ form.product_image }}
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
            <input type="submit" value="Добавить" class="btn btn-outline-secondary">
        </div>
    </form>
{% endblock %}